# Form implementation generated from reading ui file 'e:\tools\ChatE2E\src\chate2e\ui\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 600)
        LoginWindow.setStyleSheet("QMainWindow {\n"
"    background-color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.backgroundLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.backgroundLabel.setMinimumSize(QtCore.QSize(0, 200))
        self.backgroundLabel.setStyleSheet("QLabel {\n"
"    background-image: url(:/static/login_background.jpg);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"   }")
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.verticalLayout.addWidget(self.backgroundLabel)
        self.loginLayout = QtWidgets.QVBoxLayout()
        self.loginLayout.setObjectName("loginLayout")
        self.avatarLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.avatarLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.avatarLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.avatarLabel.setStyleSheet("QLabel {\n"
"    border-radius: 50px;\n"
"    background-color: white;\n"
"}")
        self.avatarLabel.setObjectName("avatarLabel")
        self.loginLayout.addWidget(self.avatarLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.usernameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.usernameEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.usernameEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #DDDDDD;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"    margin: 10px;\n"
"}")
        self.usernameEdit.setObjectName("usernameEdit")
        self.loginLayout.addWidget(self.usernameEdit)
        self.passwordEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.passwordEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.passwordEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #DDDDDD;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"    margin: 10px;\n"
"}")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.loginLayout.addWidget(self.passwordEdit)
        self.checkboxLayout = QtWidgets.QHBoxLayout()
        self.checkboxLayout.setObjectName("checkboxLayout")
        self.rememberPwdCheck = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.rememberPwdCheck.setObjectName("rememberPwdCheck")
        self.checkboxLayout.addWidget(self.rememberPwdCheck)
        self.autoLoginCheck = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.autoLoginCheck.setObjectName("autoLoginCheck")
        self.checkboxLayout.addWidget(self.autoLoginCheck)
        self.loginLayout.addLayout(self.checkboxLayout)
        self.loginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loginButton.setStyleSheet("QPushButton {\n"
"    background-color: #12B7F5;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-size: 16px;\n"
"    margin: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0EA2E4;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0B96D9;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.loginLayout.addWidget(self.loginButton)
        self.linksLayout = QtWidgets.QHBoxLayout()
        self.linksLayout.setObjectName("linksLayout")
        self.registerLink = QtWidgets.QLabel(parent=self.centralwidget)
        self.registerLink.setStyleSheet("QLabel {\n"
"    color: #12B7F5;\n"
"}")
        self.registerLink.setObjectName("registerLink")
        self.linksLayout.addWidget(self.registerLink)
        self.forgotPwdLink = QtWidgets.QLabel(parent=self.centralwidget)
        self.forgotPwdLink.setStyleSheet("QLabel {\n"
"    color: #12B7F5;\n"
"}")
        self.forgotPwdLink.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.forgotPwdLink.setObjectName("forgotPwdLink")
        self.linksLayout.addWidget(self.forgotPwdLink)
        self.loginLayout.addLayout(self.linksLayout)
        self.verticalLayout.addLayout(self.loginLayout)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "端到端聊天登录"))
        self.usernameEdit.setPlaceholderText(_translate("LoginWindow", "账号"))
        self.passwordEdit.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.rememberPwdCheck.setText(_translate("LoginWindow", "记住密码"))
        self.autoLoginCheck.setText(_translate("LoginWindow", "自动登录"))
        self.loginButton.setText(_translate("LoginWindow", "登 录"))
        self.registerLink.setText(_translate("LoginWindow", "注册账号"))
        self.forgotPwdLink.setText(_translate("LoginWindow", "找回密码"))
