[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """

[tox]
envlist = py38

[testenv]
deps = pytest
commands = pytest
"""

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
testpaths = [
    "tests"
]